trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@1
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      cd Client
      npm install
      npm start
    displayName: "npm install and build for Client"

  - script: |
      cd Server
      npm install
      npm start
    displayName: "npm install and build for Server"
