{
    "OrderID": 2,
    "OrderType": "Catalogue",
    "ItemID": 2,
    "ItemTitle": "Formal Trousers",
    "TailorID": 2,
    "TailorName": "Jane's Tailoring",
    "Measurements": {
        "height": null,
        "weight": null,
        "chest": null,
        "waist": null,
        "hips": null,
        "shoulder": null,
        "sleeves": null,
        "neck": null
    },
    "ClothUI": true,
    "Design": {
        "beltStyle": null,
        "cuffsStyle": null,
        "bottomStyle": null,
        "trouserStyle": null,
        "stitchStyle": null,
        "collarStyle": null,
        "sleevesStyle": null,
        "shoulderStyle": null,
        "neckStyle": null,
        "lacingStyle": null
    },
    "Catalogue": true,
    "CatalogueID": 123,
    "Price": 800,
    "Title": "Formal Trousers",
    "ClothingType": "Trousers",
    "OrderStatus": "Completed",
    "CustomerID": 2,
    "CustomerContactNumber": "9876543210",
    "CustomerName": "Jane Smith",
    "TailorContactNumber": "1234567890",
    "OrderAcceptanceDate": "2023-05-10T10:00:00Z",
    "OrderDeliveryDeadline": "2023-05-17T10:00:00Z",
    "PaymentStatus": "Paid",
    "Rating": 5
}